mole/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^reports/', include("reports.urls", namespace="reports")),
    url(r'', include("office.urls", namespace="office")),
    url(r'^userrole/', include("userrole.urls", namespace="role"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

office/urls.py
from django.conf.urls import url


app_name = 'office'

from office.views import OfficeCreateView, OfficeListView, OfficeUpdateView, OfficeDeleteView, DashboardView,\
    OfficeAddOfficeHeadView, OfficeAddInfoofficerView, OfficeDashboard, DistrictDashboard, OfficeDetailView,OfficeUserView,\
    OfficeKaryakram,OfficeDashboardSubmit,OfficeViewDataDetailView



urlpatterns = [

    url(r'^office/create/$', OfficeCreateView.as_view(), name='office-add'),
    url(r'^office/detail/(?P<pk>[0-9]+)/$', OfficeDetailView.as_view(), name='office-detail'),
    url(r'^office/view-data-detail/(?P<pk>[0-9]+)/$', OfficeViewDataDetailView.as_view(), name='view-data-detail'),
    url(r'^office/users/(?P<pk>[0-9]+)/$', OfficeUserView.as_view(), name='office-users'),
    url(r'^office/dashboard/(?P<pk>[0-9]+)/$', OfficeDashboard.as_view(), name='office-dashboard'),
    url(r'^office/dashboard/(?P<pk>[0-9]+)/submit/$', OfficeDashboardSubmit.as_view(), name='office-dashboard-submit'),
    url(r'^office/dashboard/(?P<pk>[0-9]+)/karyakram/$', OfficeKaryakram.as_view(), name='office-karyakram'),

    url(r'^district/dashbaord/(?P<pk>[0-9]+)/$', DistrictDashboard.as_view(), name='district-dashboard'),
    url(r'^office/update/(?P<pk>[0-9]+)/$', OfficeUpdateView.as_view(), name='office-update'),
    url(r'^office/delete/(?P<pk>[0-9]+)/$', OfficeDeleteView.as_view(), name='office-delete'),
    url(r'^office/list/$', OfficeListView.as_view(), name='office-list'),
    url(r'^office/(?P<pk>[0-9]+)/adduser/addofficehead/$', OfficeAddOfficeHeadView.as_view(), name='office-add-office-head'),
    url(r'^office/(?P<pk>[0-9]+)/adduser/addinfoofficer/$', OfficeAddInfoofficerView.as_view(), name='office-add-info-officer'),
    #url(r'^office/(?P<pk>[0-9]+)/addtype/$', OfficeAddUserView.as_view(), name='office-addtype'),
    url(r'', DashboardView.as_view(), name='dashboard'),

        ]

reports/urls.py
from django.conf.urls import url


from .views import KaryakramCreateView, KaryakramUpdateView, LakxyaCreateView, PragatiCreateView, KaryakramListView, \
    ReportView,KaryakramControlList,FirstControlList,SecondControlList,FirstControlListEdit,SecondControlListEdit,\
    SecondControlListBudget

app_name = 'reports'

urlpatterns = [
    url(r'^karyakram/list/(?P<office>[0-9]+)/$', KaryakramListView.as_view(), name='karyakram-list'),

    url(r'^karyakram/list/(?P<office>[0-9]+)/$', KaryakramListView.as_view(), name='karyakram-list'),
    url(r'^karyakram/controllist/(?P<office>[0-9]+)/$', KaryakramControlList.as_view(), name='karyakram-control-list'),
    url(r'^karyakram/firstcontrollist/(?P<office>[0-9]+)/(?P<type>[0-9]+)/$', FirstControlList.as_view(),
        name='first-control-list'),
    url(r'^karyakram/secondcontrollist/(?P<office>[0-9]+)/(?P<type>[0-9]+)/$', SecondControlList.as_view(),
        name='second-control-list'),
    url(r'^karyakram/create/(?P<office>[0-9]+)/$', KaryakramCreateView.as_view(), name='karyakram-add'),
    url(r'^list/(?P<office>[0-9]+)/(?P<awadhi>[0-9]+)/$', ReportView.as_view(), name='reports'),
    url(r'^karyakram/update/(?P<office>[0-9]+)/(?P<pk>[0-9]+)/$', KaryakramUpdateView.as_view(), name='karyakram-update'),
    url(r'^karyakram/addlaksya/(?P<office>[0-9]+)/(?P<karyakram_id>[0-9]+)/(?P<awadhi>[0-9]+)/$', LakxyaCreateView.as_view(), name='add-laksya'),
    url(r'^karyakram/addpragati/(?P<office>[0-9]+)/(?P<karyakram_id>[0-9]+)/(?P<awadhi>[0-9]+)/$', PragatiCreateView.as_view(), name='add-pragati'),

    #only for design implementation
    url(r'^karyakram/firstcontrollist/(?P<office>[0-9]+)/edit$', FirstControlListEdit.as_view(),
        name='first-control-list-edit'),
    url(r'^karyakram/secondcontrollist/(?P<office>[0-9]+)/edit/$', SecondControlListEdit.as_view(),
        name='second-control-list-edit'),
    url(r'^karyakram/secondcontrollist/(?P<office>[0-9]+)/budget$', SecondControlListBudget.as_view(),
        name='second-control-list-budget'),

        ]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = ([
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout,  {'next_page': '/users/login/'}, name='logout'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name': 'Password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name': 'Password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, {'template_name': 'Password_reset_complete.html'}, name='password_reset_complete'),
    url(r'^firstlogin/$', views.firstlogin, name='firstlogin'),
    
])

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User, Group
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db import models
from office.models import Office

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	email_confirmed = models.BooleanField(default=False)
	name = models.CharField(max_length=30, blank=True)
	phoneno = models.CharField(max_length=30, blank=True)
	assign_date = models.DateField(null=True, blank=True)
	birth_date = models.DateField(null=True, blank=True)
	photo = models.ImageField(null=True, blank=True)
	office = models.ForeignKey(Office, related_name='user_office', null=True, blank=True)
	def __str__(self):
		return str(self.user)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

office/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from models import Office
from django.contrib.auth.models import User
class OfficeForm(forms.ModelForm):
    class Meta:
        model = Office
        exclude = ()

class OfficeEditForm(forms.ModelForm):
    class Meta:
        model = Office
        exclude = ('is_project', 'is_municipality')

class UserForm(UserCreationForm):
    
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
   
    password1 = forms.CharField(initial='sa2das33@dsErZZasd')
    password2 = forms.CharField(initial='sa2das33@dsErZZasd')
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

users/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserDetailsForm(UserCreationForm):
	class Meta:
		model = User
		fields = ('password1', 'password2',)

office/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, DetailView
from django.shortcuts import render, get_object_or_404

from reports.models import KaryaKram
from .models import Office,District
from .forms import OfficeForm, UserForm,OfficeEditForm

from userrole.mixins import CreateView, UpdateView, DeleteView, OfficerMixin, AdminAssistantMixin

from django.views.generic import View
from django.shortcuts import render, redirect


from django.shortcuts import render, redirect
from django.contrib.auth.models import User, Group
from .tokens import account_activation_token
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.core.urlresolvers import reverse
from userrole.models import UserRole

class OfficeView(object):
    model = Office
    success_url = reverse_lazy('office:office-list')
    form_class = OfficeForm

class OfficeUserView(LoginRequiredMixin, TemplateView):
    template_name = 'office/users.html'

    def get_context_data(self, **kwargs):
        context = super(OfficeUserView, self).get_context_data(**kwargs)

        context['office'] = kwargs.get('pk')
        #context['head'] = UserRole.get_office_user('Office Head', kwargs.get('pk'))
        # context['assistant'] = UserRole.get_office_user('Information Officer', kwargs.get('pk'))
        return context

class OfficeKaryakram(LoginRequiredMixin, OfficeView, DetailView):
    template_name = 'reports/karyakram.html'


class OfficeDetailView(LoginRequiredMixin, OfficeView, DetailView):
    pass

class OfficeViewDataDetailView(LoginRequiredMixin, OfficeView, DetailView):
    template_name = 'office/view_data.html'


class OfficeListView(LoginRequiredMixin, AdminAssistantMixin, OfficeView, ListView):
    context_object_name = 'all_offices'
    pass


class OfficeCreateView(LoginRequiredMixin, AdminAssistantMixin, OfficeView, CreateView):
    def from_valid(self, form):
        self.object = form.save()

    
    def get_success_url(self):
        return reverse_lazy('office:office-list')

class OfficeUpdateView(LoginRequiredMixin, OfficerMixin, OfficeView, UpdateView):
    template_name = 'office/office-update.html'
    form_class = OfficeEditForm


class OfficeDeleteView(LoginRequiredMixin, AdminAssistantMixin, OfficeView, DeleteView):
    pass

class OfficeAddOfficeHeadView(LoginRequiredMixin, AdminAssistantMixin, OfficeView, View):
    def get(self, request, pk):
        user = UserForm()
        return render(request, 'office/addnewuser.html', {'form': user, 'office_id': pk, 'role':'Office Head'})

    def post(self, request, *args, **kwargs):
        form = UserForm(request.POST)
        role= request.POST.get('role')
        office = request.POST.get('office')
        if form.is_valid:
            user = form.save(commit=False)
            user.is_active = False
            user.set_unusable_password()
            user.save()
            user.profile.office = Office.objects.get(id=request.POST.get('office'))
            user.save()

            grp = Group.objects.get(name=role)
            grp.user_set.add(user)

            #email sending part
            current_site = get_current_site(request)
            subject = 'Activate Your MySite Account'
            message = render_to_string('office/accountconfirm.html',
            {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),})
            user.email_user(subject, message)
            return redirect('office:office-dashboard', pk=office)

class OfficeAddInfoofficerView(LoginRequiredMixin, AdminAssistantMixin, OfficeView, View):
    def get(self, request, pk):
        user = UserForm()
        return render(request, 'office/addnewuser.html', {'form': user, 'office_id': pk, 'role':'Information Officer'})

    def post(self, request, *args, **kwargs):
        form = UserForm(request.POST)
        role= request.POST.get('role')
        office = request.POST.get('office')
        if form.is_valid:
            user = form.save(commit=False)
            user.is_active = False
            user.set_unusable_password()
            user.save()
            user.profile.office = Office.objects.get(id=request.POST.get('office'))
            user.save()

            grp = Group.objects.get(name=role)
            grp.user_set.add(user)

            #email sending part
            current_site = get_current_site(request)
            subject = 'Activate Your MySite Account'
            message = render_to_string('office/accountconfirm.html',
            {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),})
            user.email_user(subject, message)
            return redirect('office:office-dashboard', pk=office)


class DashboardView(LoginRequiredMixin, TemplateView):

    template_name = "office/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['offices'] = Office.objects.all()
        context['submission_count'] = 0
        context['offices_count'] = Office.objects.all().count()
        context['users_count'] = User.objects.all().count()

        return context



class OfficeDashboard(LoginRequiredMixin, TemplateView):

    template_name = "office/office_dashboard.html"
    def get_context_data(self, **kwargs):
        context = super(OfficeDashboard, self).get_context_data(**kwargs)
        office = Office.objects.get(pk=kwargs.get('pk'))

        context['office'] = office
        context['karyakrams'] = KaryaKram.objects.filter(office=office)
        return context


class OfficeDashboardSubmit(LoginRequiredMixin, TemplateView):

    template_name = "office/office_dashboard_submit.html"
    def get_context_data(self, **kwargs):
        context = super(OfficeDashboardSubmit, self).get_context_data(**kwargs)
        office = Office.objects.get(pk=kwargs.get('pk'))

        context['office'] = office
        return context


class DistrictDashboard(LoginRequiredMixin, TemplateView):

    template_name = "office/district_dashboard.html"

    def get_context_data(self, **kwargs):
        context = super(DistrictDashboard, self).get_context_data(**kwargs)
        district = District.objects.get(pk=kwargs.get('pk'))

        context['district'] = district
        context['offices'] = Office.objects.filter(district=district)
        return context

users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404, redirect
from .imagecropper import PhotoForm
from django.shortcuts import render
from django.contrib.auth.models import User

from django.contrib.auth import login, authenticate
from django.views.generic import View
# from .tokens import account_activation_token
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode

from .models import Profile
from .forms import UserDetailsForm
from userrole.forms import UserRoleForm
from userrole.mixins import LoginRequiredMixin, SuperAdminMixin, CreateView, UpdateView, DeleteView
from userrole.models import UserRole as Role, UserRole

from django.shortcuts import redirect
from django.urls import reverse_lazy

class UserRoleView(object):
    model = UserRole
    success_url = reverse_lazy('role:user-role-list')
    form_class = UserRoleForm         



def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None


    if user is not None and account_activation_token.check_token(user, token):

        profile = get_object_or_404(Profile, user=uid)
        photoform = PhotoForm(request.POST or None, instance=profile)
        userform = UserDetailsForm()


        return render(request, 'profiledetails.html', {'uid': uidb64, 'photoform':photoform, 'userform':userform})
    else:
    	return redirect('users:login')

    		#return redirect('question_detail', pk=question.pk)
    	#return redirect('supa:listoffice')





def firstlogin(request, *args, **kwargs):

    if request.method=='POST':

    	password1 = request.POST.get('password1')
    	password2 = request.POST.get('password2')

    	if password2 == password1:
        	usrid = request.POST.get('uidb64')
        	uid = force_text(urlsafe_base64_decode(usrid))
        	user = User.objects.get(pk=uid)
        	user.profile.email_confirmed = True
        	user.set_password(password2)
        	user.is_active = True
        	user.save()

                office = user.profile.office.id

                profile = get_object_or_404(Profile, user=uid)
            	user1 = authenticate(username=user.username, password=password2)
            	form = PhotoForm(request.POST, request.FILES, instance=profile)

        	if form.is_valid():
        		form.save()

        	login(request, user1)

        	return redirect('office:office-dashboard', pk=office)
    	return redirect('error')

office/templates/office/accountconfirm.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

office/templates/office/add_office_detail.html
<form class = "" action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{% include 'office/form_template.html' %}
	<input type="hidden" name="office_id" value="{{ id }}">
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-success">पेश गर्नुहोस्</button>
		</div>
	</div>

</form>

office/templates/office/form_template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class="con																																				trol-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

office/templates/office/office_dashboard.html
{% extends "base_layout.html" %}
{% load staticfiles %}
{% load filters %}

{% block title %}{{office}}{% endblock title %}

{% block content %}

<!--Main Content Area Starts-->
		<section id="app-section">
			<div class="bg-white padding margin-top-lg">
				<div class="row">
					<div class="col-md-4 col-lg-3">
						<!--Office Image-->
						<div class="thumbnail">
							<img src="{% static 'assets/images/img-office.png' %}" alt="...">
							<div class="caption">
								<h5>{{office}}</h5>
							</div>
						</div>
					</div>
					<div class="col-md-8 col-lg-9">
						<!--Office Map-->
						<div id="map" style="width:100%;height:279px"></div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-3">
					<a href="{% url 'office:office-detail' office.id %}" title="" class="btn btn-sm btn-primary btn-block margin-top-lg">View Detail</a>
				</div>
				<div class="col-md-3">
					<a href="{% url 'office:office-users' office.id %}" title="" class="btn btn-sm btn-primary btn-block margin-top-lg">Users</a>
				</div>
				<div class="col-md-3">
					<a href="{% url 'office:office-dashboard-submit' office.id %}" title="" class="btn btn-sm btn-primary btn-block margin-top-lg">Submit File</a>
				</div>
				<div class="col-md-3">
					<a href="{% url 'office:office-karyakram' office.id %}" title="" class="btn btn-sm btn-primary btn-block margin-top-lg">कार्यक्रम</a>
				</div>
			</div>
			<ul class="different-list margin-top-lg">
				<li>
					<div class="table-responsive">
						<table class="table table-bordered table-hover">
							<thead>
								<tr>
									<th rowspan="2">वार्षिक/चौमासिक लक्ष्य र प्रगति</th>
									<th>लक्ष्य</th>
									<th><a href="{% url 'reports:first-control-list' office.id 0 %}" title="" class="btn btn-xs btn-primary">प्रथम</a></th>
									<th><a href="" title="" class="btn btn-xs btn-primary">चौमासिक</a></th>
									<th><a href="#" title="" class="btn btn-xs btn-primary">वार्षिक</a></th>
								</tr>
								<tr>
									<th>प्रगति</th>
									<th><a href="{% url 'reports:second-control-list' office.id 1 %}" title="" class="btn btn-xs btn-primary">प्रथम</a></th>
									<th><a href="#" title="" class="btn btn-xs btn-primary">चौमासिक</a></th>
									<th><a href="#" title="" class="btn btn-xs btn-primary">वार्षिक</a></th>
								</tr>
							</tbody>
						</table>
					</div>
				</li>
				<li>
					<div class="table-responsive">
						<table class="table table-bordered table-hover">
							<thead>
								<tr>
									<th>मासिक लक्ष्य र प्रगति</th>
									<th><a href="#" title="" class="btn btn-xs btn-primary"><i class="fa fa-eye"></i> View</a></th>
									<th><a href="#" title="" class="btn btn-xs btn-primary"><i class="fa fa-edit"></i> Edit</a></th>
								</tr>
								<tr>
									<th>कार्य सम्पादन सूचक </th>
									<th><a href="#" title="" class="btn btn-xs btn-primary"><i class="fa fa-eye"></i> View</a></th>
									<th><a href="#" title="" class="btn btn-xs btn-primary"><i class="fa fa-edit"></i> Edit</a></th>
								</tr>
								<tr>
									<th>बजेट बक्तब्य </th>
									<th><a href="#" title="" class="btn btn-xs btn-primary"><i class="fa fa-eye"></i> View</a></th>
									<th><a href="#" title="" class="btn btn-xs btn-primary"><i class="fa fa-edit"></i> Edit</a></th>
								</tr>
								<tr>
									<th>सचिब बैठक प्रगति </th>
									<th><a href="#" title="" class="btn btn-xs btn-primary"><i class="fa fa-eye"></i> View</a></th>
									<th><a href="#" title="" class="btn btn-xs btn-primary"><i class="fa fa-edit"></i> Edit</a></th>
								</tr>
								<tr>
									<th>बार्षिक चौमासिक प्रगति  </th>
									<th><a href="#" title="" class="btn btn-xs btn-primary"><i class="fa fa-eye"></i> View</a></th>
									<th><a href="#" title="" class="btn btn-xs btn-primary"><i class="fa fa-edit"></i> Edit</a></th>
								</tr>
							</tbody>
						</table>
					</div>
				</li>
			</ul>
		</section>
		<div class="clearfix"></div>
		<!--Main Content Area Ends-->

{% endblock content %}


		{% block extra_scripts %}
       		 <script>window.jQuery || document.write('<script src="{% static 'assets/js/vendor/jquery.min.js' %}"><\/script>')</script>

            <script>
                function myMap() {
                    var myCenter = new google.maps.LatLng(51.508742,-0.120850);
                    var mapCanvas = document.getElementById("map");
                    var mapOptions = {center: myCenter, zoom: 5};
                    var map = new google.maps.Map(mapCanvas, mapOptions);
                    var marker = new google.maps.Marker({position:myCenter});
                    marker.setMap(map);
                }
            </script>
            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBDmkU1cjj2GkxzKoYWZV987q0sIGCL3Ps&callback=myMap"></script>

        {% endblock extra_scripts %}

office/templates/office/office_dashboard_submit.html
{% extends "base_layout.html" %}
{% load staticfiles %}
{% load filters %}

{% block title %}{% endblock title %}

{% block content %}

		<!--Main Content Area Starts-->
		<section id="app-section">
			<ol class="breadcrumb no-margin margin-top-lg">
			  <li><a href="{% url 'office:dashboard' %}">गृह पृष्ठ</a></li>
			  <li><a href="{% url 'office:office-dashboard' office.id %}">वैदेशिक रोजगार विभाग</a></li>
			  <li class="active">Submit File</li>
			</ol>
			<div class="bg-white padding margin-top-lg">
				<div class="table-responsive">
							<table class="table table-hover">
								<thead>
									<tr>
										<th>नाम</th>
										<th>सुरक्षित गर्नुहोस</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>फाइल नाम</td>
										<td><a href="#" title="" class="btn btn-xs btn-primary"><i class="fa fa-download"></i> Download</a></td>
									</tr>
									<tr>
										<td>फाइल नाम</td>
										<td><a href="#" title="" class="btn btn-xs btn-primary"><i class="fa fa-download"></i> Download</a></td>
									</tr>
									<tr>
										<td>फाइल नाम</td>
										<td><a href="#" title="" class="btn btn-xs btn-primary"><i class="fa fa-download"></i> Download</a></td>
									</tr>
									<tr>
										<td>फाइल नाम</td>
										<td><a href="#" title="" class="btn btn-xs btn-primary"><i class="fa fa-download"></i> Download</a></td>
									</tr>
									<tr>
										<td>फाइल नाम</td>
										<td><a href="#" title="" class="btn btn-xs btn-primary"><i class="fa fa-download"></i> Download</a></td>
									</tr>
									<tr>
										<td>फाइल नाम</td>
										<td><a href="#" title="" class="btn btn-xs btn-primary"><i class="fa fa-download"></i> Download</a></td>
									</tr>
								</tbody>
							</table>
				</div>
						<nav aria-label="Page navigation">
						  <ul class="pagination">
							<li>
							  <a href="#" aria-label="Previous">
								<span aria-hidden="true">&laquo;</span>
							  </a>
							</li>
							<li><a href="#">1</a></li>
							<li><a href="#">2</a></li>
							<li><a href="#">3</a></li>
							<li><a href="#">4</a></li>
							<li><a href="#">5</a></li>
							<li>
							  <a href="#" aria-label="Next">
								<span aria-hidden="true">&raquo;</span>
							  </a>
							</li>
						  </ul>
						</nav>
			</div>
		</section>
		<div class="clearfix"></div>
		<!--Main Content Area Ends-->

{% endblock content %}

{% block extra_scripts %}{% endblock extra_scripts %}

office/templates/office/office_form.html
<form class = "" action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{% include 'office/form_template.html' %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-success">पेश गर्नुहोस्</button>
		</div>
	</div>

</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

office/templates/office/office_list.html
	{% if all_offices %}
	    <h1>All Offices</h1>
	    <ul>
	        {% for office in all_offices %}
	       <h1>{{ office.id }}. {{ office.name }}</h1><a href="{% url 'office:office-update' office.id %}"></a>
	        {% endfor %}
	    </ul>
	{% else %}
	    <h3>No Offices</h3>
	{%endif%}