mole/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^reports/', include("reports.urls", namespace="reports")),
    url(r'', include("office.urls", namespace="office")),
    url(r'^userrole/', include("userrole.urls", namespace="role"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

office/urls.py
from django.conf.urls import url


app_name = 'office'

from office.views import OfficeCreateView, OfficeListView, OfficeUpdateView, OfficeDeleteView, DashboardView,\
    OfficeAddOfficeHeadView, OfficeAddInfoofficerView, OfficeDashboard, DistrictDashboard, OfficeDetailView,OfficeUserView,\
    OfficeKaryakram,OfficeDashboardSubmit,OfficeViewDataDetailView



urlpatterns = [

    url(r'^office/create/$', OfficeCreateView.as_view(), name='office-add'),
    url(r'^office/detail/(?P<pk>[0-9]+)/$', OfficeDetailView.as_view(), name='office-detail'),
    url(r'^office/view-data-detail/(?P<pk>[0-9]+)/$', OfficeViewDataDetailView.as_view(), name='view-data-detail'),
    url(r'^office/users/(?P<pk>[0-9]+)/$', OfficeUserView.as_view(), name='office-users'),
    url(r'^office/dashboard/(?P<pk>[0-9]+)/$', OfficeDashboard.as_view(), name='office-dashboard'),
    url(r'^office/dashboard/(?P<pk>[0-9]+)/submit/$', OfficeDashboardSubmit.as_view(), name='office-dashboard-submit'),
    url(r'^office/dashboard/(?P<pk>[0-9]+)/karyakram/$', OfficeKaryakram.as_view(), name='office-karyakram'),

    url(r'^district/dashbaord/(?P<pk>[0-9]+)/$', DistrictDashboard.as_view(), name='district-dashboard'),
    url(r'^office/update/(?P<pk>[0-9]+)/$', OfficeUpdateView.as_view(), name='office-update'),
    url(r'^office/delete/(?P<pk>[0-9]+)/$', OfficeDeleteView.as_view(), name='office-delete'),
    url(r'^office/list/$', OfficeListView.as_view(), name='office-list'),
    url(r'^office/(?P<pk>[0-9]+)/adduser/addofficehead/$', OfficeAddOfficeHeadView.as_view(), name='office-add-office-head'),
    url(r'^office/(?P<pk>[0-9]+)/adduser/addinfoofficer/$', OfficeAddInfoofficerView.as_view(), name='office-add-info-officer'),
    #url(r'^office/(?P<pk>[0-9]+)/addtype/$', OfficeAddUserView.as_view(), name='office-addtype'),
    url(r'', DashboardView.as_view(), name='dashboard'),

        ]

reports/urls.py
from django.conf.urls import url


from .views import KaryakramCreateView, KaryakramUpdateView, LakxyaCreateView, PragatiCreateView, KaryakramListView, \
    ReportView,KaryakramControlList,FirstControlList,SecondControlList,FirstControlListEdit,SecondControlListEdit,\
    SecondControlListBudget

app_name = 'reports'

urlpatterns = [
    url(r'^karyakram/list/(?P<office>[0-9]+)/$', KaryakramListView.as_view(), name='karyakram-list'),

    url(r'^karyakram/list/(?P<office>[0-9]+)/$', KaryakramListView.as_view(), name='karyakram-list'),
    url(r'^karyakram/controllist/(?P<office>[0-9]+)/$', KaryakramControlList.as_view(), name='karyakram-control-list'),
    url(r'^karyakram/firstcontrollist/(?P<office>[0-9]+)/(?P<type>[0-9]+)/$', FirstControlList.as_view(),
        name='first-control-list'),
    url(r'^karyakram/secondcontrollist/(?P<office>[0-9]+)/(?P<type>[0-9]+)/$', SecondControlList.as_view(),
        name='second-control-list'),
    url(r'^karyakram/create/(?P<office>[0-9]+)/$', KaryakramCreateView.as_view(), name='karyakram-add'),
    url(r'^list/(?P<office>[0-9]+)/(?P<awadhi>[0-9]+)/$', ReportView.as_view(), name='reports'),
    url(r'^karyakram/update/(?P<office>[0-9]+)/(?P<pk>[0-9]+)/$', KaryakramUpdateView.as_view(), name='karyakram-update'),
    url(r'^karyakram/addlaksya/(?P<office>[0-9]+)/(?P<karyakram_id>[0-9]+)/(?P<awadhi>[0-9]+)/$', LakxyaCreateView.as_view(), name='add-laksya'),
    url(r'^karyakram/addpragati/(?P<office>[0-9]+)/(?P<karyakram_id>[0-9]+)/(?P<awadhi>[0-9]+)/$', PragatiCreateView.as_view(), name='add-pragati'),

    #only for design implementation
    url(r'^karyakram/firstcontrollist/(?P<office>[0-9]+)/edit$', FirstControlListEdit.as_view(),
        name='first-control-list-edit'),
    url(r'^karyakram/secondcontrollist/(?P<office>[0-9]+)/edit/$', SecondControlListEdit.as_view(),
        name='second-control-list-edit'),
    url(r'^karyakram/secondcontrollist/(?P<office>[0-9]+)/budget$', SecondControlListBudget.as_view(),
        name='second-control-list-budget'),

        ]

reports/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from office.models import Office


class FiscalYear(models.Model):
    date_range = models.CharField(max_length=255)

    def __unicode__(self):
        return u'%s' % (self.date_range)

class OfficeSetting(models.Model):
    fiscal_year = models.ForeignKey(FiscalYear, verbose_name="Arthik Barsa", blank=True, null=True, related_name="settings")
    office = models.OneToOneField(Office, verbose_name="",related_name="settings", on_delete=models.CASCADE)

AWADHI_CHOICES = (
        (0, 'बार्षिक'),
        (1, 'प्रथम'),
        (2, 'दितिय'),
        (3, 'तृतीय'),
    )


class KaryaKram(models.Model):
    karyakram = models.ForeignKey('self', verbose_name="कार्यक्रम", blank=True, null=True, related_name="parent", help_text="")
    name = models.CharField(max_length=255, verbose_name="कार्यक्रम",)
    office = models.ForeignKey(Office, verbose_name="कार्यालय", related_name="karyakram")
    code = models.CharField(verbose_name="कोड", max_length=15, null=True, blank=True, help_text="")
    unit = models.CharField(verbose_name="युनिट", max_length=15)
    kriyakalap = models.CharField(verbose_name="कृयाकलाप", max_length=15, null=True, blank=True, help_text="")

    @property
    def is_valid(self):
        return True if self.parent.all().count() else False

    def __unicode__(self):
		return u'%s'%(self.name)


class Lakxya(models.Model):
    karyakram = models.ForeignKey(KaryaKram, verbose_name=" कार्यक्रम", related_name="lakxya", help_text="")
    fiscal_year = models.ForeignKey(FiscalYear, verbose_name="आर्थिक-वर्ष", related_name="lakxya")
    paridam = models.FloatField(verbose_name="परिदम", default=0.00)
    var = models.FloatField(verbose_name="भार", default=0.00)
    budget = models.FloatField(verbose_name="बजेट", default=0.00)
    awadhi = models.IntegerField(verbose_name="अवधि", choices=AWADHI_CHOICES, default=0)


class Pragati(models.Model):
    karyakram = models.ForeignKey(KaryaKram, verbose_name="कार्यक्रम", related_name="pragati", help_text="")
    fiscal_year = models.ForeignKey(FiscalYear, verbose_name="आर्थिक-वर्ष", related_name="pragati")
    paridam = models.FloatField(verbose_name="परिदम", default=0.00)
    var = models.FloatField(verbose_name="भार", default=0.00)
    budget = models.FloatField(verbose_name="बजेट", default=0.00)
    awadhi = models.IntegerField(verbose_name="अवधि", choices=AWADHI_CHOICES, default=1)


class PragatiHistory(models.Model):
    paridam = models.FloatField(verbose_name="परिदम", default=0.00)
    var = models.FloatField(verbose_name="भार", default=0.00)
    budget = models.FloatField(verbose_name="बजेट", default=0.00)
    pragati = models.ForeignKey(Pragati, verbose_name="प्रगती", related_name="history")


class LakxyaHistory(models.Model):
    paridam = models.FloatField(verbose_name="परिदम", default=0.00)
    var = models.FloatField(verbose_name="भार", default=0.00)
    budget = models.FloatField(verbose_name="बजेट", default=0.00)
    lakxya = models.ForeignKey(Lakxya, verbose_name="लक्ष्य",  related_name="history")

reports/forms.py
from django import forms

from reports.models import KaryaKram, Lakxya, Pragati



class KaryakramForm(forms.ModelForm):
    class Meta:
        model = KaryaKram
        exclude = ('office',)


class LakxyaForm(forms.ModelForm):
    class Meta:
        model = Lakxya
        exclude = ('karyakram','fiscal_year', 'awadhi')


class PragatiForm(forms.ModelForm):
    class Meta:
        model = Pragati
        exclude = ('karyakram','fiscal_year', 'awadhi')

reports/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import transaction
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import FormView, ListView

from office.models import Office
from reports.forms import KaryakramForm, LakxyaForm, PragatiForm
from reports.models import KaryaKram, Lakxya, Pragati
from userrole.mixins import CreateView, UpdateView, OfficeView, OfficerMixin
from django.core.urlresolvers import reverse
from django.db.models import Prefetch


class KaryakramView(object):
    model = KaryaKram
    form_class = KaryakramForm

class LakxyaView(object):
    model = Lakxya
    form_class = LakxyaForm

class PragatiView(object):
    model = Pragati
    form_class = PragatiForm



class KaryakramCreateView(OfficeView, KaryakramView, CreateView):

    def get(self, request, *args, **kwargs):
        office = self.kwargs['office']
        return render(request, 'reports/karyakram_form.html', {'office': office},)


    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.office = Office(pk=self.kwargs.get('office'))
        self.object.save()
        return redirect(reverse('reports:add-laksya',args=(self.object.office.id, self.object.id, 0)))

class KaryakramUpdateView(OfficeView, KaryakramView, UpdateView):
    pass


class KaryakramListView(OfficeView, KaryakramView, OfficerMixin, ListView):
    def get_context_data(self, **kwargs):
        data = super(KaryakramListView, self).get_context_data(**kwargs)
        data['office'] = self.kwargs.get('office')
        return data

    def get_queryset(self):
        # filter fiscal year == office.settings.fiscal year
        return super(KaryakramListView, self).get_queryset().filter(office__id=self.kwargs.get('office'))

class LakxyaCreateView(OfficeView, LakxyaView, FormView):
    template_name = 'reports/lakxya_form.html'


    def get(self, request, *args, **kwargs):
        awadhi = self.kwargs['awadhi']
        karyakram_id = self.kwargs['karyakram_id']
        karyakram = KaryaKram.objects.get(pk=karyakram_id)
        laxya, created = Lakxya.objects.get_or_create(karyakram=karyakram, fiscal_year_id=1, awadhi=awadhi)
        form = LakxyaForm(instance=laxya)
        return render(request, 'reports/lakxya_form.html', {'form': form,'awadhi': awadhi, 'karyakram':karyakram},)


    def form_valid(self, form):
        lakxya = Lakxya.objects.get(pk=form.data.get('lakxya'))
        lakxya.paridam = form.cleaned_data['paridam']
        lakxya.var = form.cleaned_data['var']
        lakxya.budget = form.cleaned_data['budget']
        lakxya.save()
        # correct url to redirect after lakxya save and fill pragati
        

        if lakxya.awadhi == 0:
            return redirect(reverse('reports:add-laksya',args=(lakxya.karyakram.office.id, lakxya.karyakram.id, 1)))
        else:
            return redirect(reverse('office:office-dashboard',args=(lakxya.karyakram.office.id,)))

class PragatiCreateView(OfficeView, PragatiView, CreateView):
    def get(self, request, *args,  **kwargs):
        awadhi = self.kwargs['awadhi']
        karyakram_id = self.kwargs['karyakram_id']
        karyakram = KaryaKram.objects.get(pk=karyakram_id)
        pragati, created = Pragati.objects.get_or_create(karyakram=karyakram, fiscal_year_id=1, awadhi=awadhi)
        form = PragatiForm(instance=pragati)
        return render(request, 'reports/pragati_form.html', {'form': form,'awadhi': awadhi, 'karyakram':karyakram},)


    def form_valid(self, form):
        pragati = Pragati.objects.get(pk=form.data.get('pragati'))
        pragati.paridam = form.cleaned_data['paridam']
        pragati.var = form.cleaned_data['var']
        pragati.budget = form.cleaned_data['budget']
        pragati.save()
        # correct url to redirect after lakxya save and fill pragati
        if pragati.awadhi == 1:
            return redirect(reverse('reports:add-laksya',args=(pragati.karyakram.office.id, pragati.karyakram.id, 2)))
        else:
            return redirect(reverse('office:office-dashboard',args=(pragati.karyakram.office.id,)))


class ReportView(OfficeView, OfficerMixin, KaryakramView, ListView):
    template_name = 'reports/reports.html'

    def get_context_data(self, **kwargs):
        data = super(ReportView, self).get_context_data(**kwargs)
        data['office'] = self.kwargs.get('office')
        data['awadhi'] = self.kwargs.get('awadhi')
        return data

    def get_queryset(self):
        # filter fiscal year == office.settings.fiscal year
        qs =  KaryaKram.objects.filter(office__id=self.kwargs.get("office"), lakxya__awadhi=0, pragati__awadhi=1).\
            prefetch_related("lakxya", "pragati")
        return qs


class KaryakramControlList(OfficeView, OfficerMixin, KaryakramView, ListView):
    template_name = 'reports/karyakram_control.html'

    def get_context_data(self, **kwargs):
        data = super(KaryakramControlList, self).get_context_data(**kwargs)
        data['office'] = self.kwargs.get('office')
        data['awadhi'] = self.kwargs.get('awadhi')
        return data

    def get_queryset(self):
        qs = KaryaKram.objects.filter(office__id=self.kwargs.get("office"), karyakram__isnull=True).prefetch_related(Prefetch("parent", to_attr='childs'))

        return qs

class FirstControlList(OfficeView, OfficerMixin, KaryakramView, ListView):

    def get(self, request, *args, **kwargs):
        office = self.kwargs['office']
        return render(request, 'reports/First_control.html', {'office': office}, )


class SecondControlList(OfficeView, OfficerMixin, KaryakramView, ListView):
    def get(self, request, *args, **kwargs):
        office = self.kwargs['office']
        return render(request, 'reports/second_control.html', {'office': office}, )

#only for design implementation
class FirstControlListEdit(OfficeView, OfficerMixin, KaryakramView, ListView):
    def get(self, request, *args, **kwargs):
        office = self.kwargs['office']
        return render(request, 'reports/first_controllist_edit.html', {'office': office}, )


class SecondControlListEdit(OfficeView, OfficerMixin, KaryakramView, ListView):
    def get(self, request, *args, **kwargs):
        office = self.kwargs['office']
        return render(request, 'reports/second_controllist_edit.html', {'office': office}, )


class SecondControlListBudget(OfficeView, OfficerMixin, KaryakramView, ListView):
    def get(self, request, *args, **kwargs):
        office = self.kwargs['office']
        return render(request, 'reports/budget.html', {'office': office}, )

templates/reports/First_control.html
{% extends "base_layout.html" %}
{% load staticfiles %}
{% load filters %}

{% block title %}Karyakrams{% endblock title %}

{% block content %}
<!--Main Content Area Starts-->
		<section id="app-section">
			<ol class="breadcrumb no-margin margin-top-lg">
			  <li><a href="{% url 'office:dashboard' %}">गृह पृष्ठ</a></li>
			  <li><a href="{% url 'office:office-dashboard' office %}">वैदेशिक रोजगार विभाग</a></li>
			  <li class="active">वार्षिक/ चौमासिक लक्ष्य</li>
			</ol>
			<div class="bg-white padding margin-top-lg">
				<div class="app-page-header">
					<div class="row">
						<div class="col-md-5">
							<h4>वार्षिक/ चौमासिक लक्ष्य</h4>
						</div>
						<div class="col-md-2">
							<select class="form-control input-sm">
							  <option>10</option>
							  <option>20</option>
							  <option>30</option>
							  <option>40</option>
							  <option>50</option>
							</select>
						</div>
						<div class="col-md-5">
							<div class="action-holder">
								<a href="#" title="" class="btn btn-xs btn-default"><i class="fa fa-file-code-o"></i> CSV</a>
								<a href="#" title="" class="btn btn-xs btn-default"><i class="fa fa-file-excel-o"></i> Excel</a>
								<a href="#" title="" class="btn btn-xs btn-default"><i class="fa fa-file-pdf-o"></i> PDF</a>
								<a href="#" title="" class="btn btn-xs btn-default"><i class="fa fa-print"></i> Print</a>
							</div>
						</div>
					</div>
				</div>
				<div class="table-responsive">
					<table class="table table-bordered table-hover">
						<thead>
							<tr>
								<th>क्र. म.</th>
								<th>कार्यक्रम</th>
								<th colspan="3">वार्षिक लक्ष्य</th>
								<th colspan="3">प्रथम</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>१.</td>
								<td>कार्यक्रम (१)</td>
								<td>१.</td>
								<td>१.</td>
								<td>१.</td>
								<td></td>
								<td></td>
								<td></td>
								<td><a href="{% url 'reports:first-control-list-edit' office %}" title="" class="btn btn-xs btn-primary"><i class="fa fa-edit"></i></a></td>
							</tr>
							<tr>
								<td>१.</td>
								<td>कार्यक्रम (१)</td>
								<td>१.</td>
								<td>१.</td>
								<td>१.</td>
								<td></td>
								<td></td>
								<td></td>
								<td><a href="{% url 'reports:first-control-list-edit' office %}" title="" class="btn btn-xs btn-primary"><i class="fa fa-edit"></i></a></td>
							</tr>
							<tr>
								<td>१.</td>
								<td>कार्यक्रम (१)</td>
								<td>१.</td>
								<td>१.</td>
								<td>१.</td>
								<td></td>
								<td></td>
								<td></td>
								<td><a href="l-first-edit.php" title="" class="btn btn-xs btn-primary"><i class="fa fa-edit"></i></a></td>
							</tr>
							<tr>
								<td>१.</td>
								<td>कार्यक्रम (१)</td>
								<td>१.</td>
								<td>१.</td>
								<td>१.</td>
								<td></td>
								<td></td>
								<td></td>
								<td><a href="l-first-edit.php" title="" class="btn btn-xs btn-primary"><i class="fa fa-edit"></i></a></td>
							</tr>
						</tbody>
					</table>
				</div>
				<nav aria-label="Page navigation">
					<ul class="pagination">
						<li>
							<a href="#" aria-label="Previous">
								<span aria-hidden="true">&laquo;</span>
							</a>
						</li>
						<li><a href="#">1</a></li>
						<li><a href="#">2</a></li>
						<li><a href="#">3</a></li>
						<li><a href="#">4</a></li>
						<li><a href="#">5</a></li>
						<li>
							<a href="#" aria-label="Next">
								<span aria-hidden="true">&raquo;</span>
							</a>
						</li>
					</ul>
				</nav>
			</div>
		</section>
		<div class="clearfix"></div>
		<!--Main Content Area Ends-->
{% endblock content %}

templates/reports/budget.html
{% extends "base_layout.html" %}
{% load staticfiles %}
{% load filters %}

{% block title %}Karyakrams{% endblock title %}

{% block content %}


		<!--Main Content Area Starts-->
		<section id="app-section">
			<ol class="breadcrumb no-margin margin-top-lg">
			  <li><a href="{% url 'office:dashboard' %}">गृह पृष्ठ</a></li>
			  <li><a href="{% url 'office:office-dashboard' office %}">वैदेशिक रोजगार विभाग</a></li>
			  <li><a href="{% url 'reports:second-control-list' office 1 %}">वार्षिक/ चौमासिक लक्ष्य</a></li>
			  <li class="active">बजेट</li>
			</ol>
			<div class="bg-white padding margin-top-lg">
				<div class="app-page-header">
					<h4>बजेट थप्नुहोस</h4>
				</div>
				<form>
					<div class="form-group">
						<label for="input1">१. बजेट शिर्षक न. </label>
						<input type="text" class="form-control" id="input1">
					</div>
					<div class="form-group">
						<label for="input2">२. यस अवधिको बजेट रु</label>
						<input type="text" class="form-control" id="input2">
					</div>
					<hr>
					<div class="form-group">
						<label>क. आन्तरिक</label>
					</div>
					<div class="form-group">
						<label for="input3">i. नेपाल सरकार</label>
						<input type="text" class="form-control" id="input3">
					</div>
					<div class="form-group">
						<label for="input4">ii. संस्था</label>
						<input type="text" class="form-control" id="input4">
					</div>
					<div class="form-group">
						<label for="input5">iii. जन सहभागिता</label>
						<input type="text" class="form-control" id="input5">
					</div>
					<hr>
					<div class="form-group">
						<label>ख. वैदेसिक</label>
					</div>
					<div class="form-group">
						<label for="input6">i. ऋण</label>
						<input type="text" class="form-control" id="input6">
					</div>
					<div class="form-group">
						<label for="input7">ii. अनुदान</label>
						<input type="text" class="form-control" id="input7">
					</div>
					<hr>
					<div class="form-group">
						<label for="input8">ग. दार्ति संस्था</label>
						<input type="text" class="form-control" id="input8">
					</div>
					<hr>
					<div class="form-group">
						<label>३. यस अवधिको खर्च रु</label>
					</div>
					<div class="form-group">
						<label for="input9">i. आन्तरिक</label>
						<input type="text" class="form-control" id="input9">
					</div>
					<div class="form-group">
						<label for="input10">ii. वैदेशिक</label>
						<input type="text" class="form-control" id="input10">
					</div>
					<hr>
					<div class="form-group">
						<label for="input11">४. चौमासिक बजेटको खर्च प्रतिसत</label>
						<input type="text" class="form-control" id="input11">
					</div>
					<div class="form-group">
						<label for="input12">५. सुरु देखि यस अवधिसम्मको कुल खर्च(कुल लागतको तुलनामा)</label>
						<input type="text" class="form-control" id="input12">
					</div>
					<div class="form-group">
						<label for="input13">६. बितेको समय प्रतिसतमा (कुल अवधिको तुलनामा)</label>
						<input type="text" class="form-control" id="input13">
					</div>
					<button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-save"></i> Save</button>
				</form>
			</div>
		</section>
		<div class="clearfix"></div>
		<!--Main Content Area Ends-->


{% endblock content %}

templates/reports/form_template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class="con																																				trol-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

templates/reports/second_control.html
{% extends "base_layout.html" %}
{% load staticfiles %}
{% load filters %}

{% block title %}{{office}}{% endblock title %}

{% block content %}
<!--Main Content Area Starts-->
		<section id="app-section">
			<ol class="breadcrumb no-margin margin-top-lg">
			  <li><a href="{% url 'office:dashboard' %}">गृह पृष्ठ</a></li>
			  <li><a href="{% url 'office:office-dashboard' office %}">वैदेशिक रोजगार विभाग</a></li>
			  <li class="active">वार्षिक/ चौमासिक लक्ष्य</li>
			</ol>
			<div class="bg-white padding margin-top-lg">
				<div class="app-page-header">
					<div class="row">
						<div class="col-md-5">
							<h4>वार्षिक/ चौमासिक लक्ष्य</h4>
						</div>
						<div class="col-md-2">
							<select class="form-control input-sm">
							  <option>10</option>
							  <option>20</option>
							  <option>30</option>
							  <option>40</option>
							  <option>50</option>
							</select>
						</div>
						<div class="col-md-5">
							<div class="action-holder">
								<a href="#" title="" class="btn btn-xs btn-default"><i class="fa fa-file-code-o"></i> CSV</a>
								<a href="#" title="" class="btn btn-xs btn-default"><i class="fa fa-file-excel-o"></i> Excel</a>
								<a href="#" title="" class="btn btn-xs btn-default"><i class="fa fa-file-pdf-o"></i> PDF</a>
								<a href="#" title="" class="btn btn-xs btn-default"><i class="fa fa-print"></i> Print</a>
								<a href="{% url 'reports:second-control-list-budget' office %}" title="" class="btn btn-xs btn-success"><i class="fa fa-money"></i> Budget</a>
							</div>
						</div>
					</div>
				</div>
				<div class="table-responsive">
					<table class="table table-bordered table-hover">
						<thead>
							<tr>
								<th>क्र. म.</th>
								<th>कार्यक्रम</th>
								<th colspan="3">वार्षिक लक्ष्य</th>
								<th colspan="3">पहिलो चौमासिक लक्ष्य</th>
								<th colspan="3">पहिलो चौमासिक प्रगति</th>
								<th>भौतिक प्रगती</th>
								<th>आर्थिक प्रगती</th>
								<th colspan="2">प्रतिवेदन</th>
								<th>हाल सम्मको प्रगती</th>
								<th>कैफियत</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>१.</td>
								<td>१.</td>
								<td>१.</td>
								<td>१.</td>
								<td>१.</td>
								<td>१.</td>
								<td>१.</td>
								<td>१.</td>
								<td>१.</td>
								<td>१.</td>
								<td>१.</td>
								<td>१.</td>
								<td>१.</td>
								<td>१.</td>
								<td>१.</td>
								<td>१.</td>

								<td><a href="{% url 'reports:second-control-list-edit' office %}" title="" class="btn btn-xs btn-primary"><i class="fa fa-edit"></i></a></td>
							</tr>

						</tbody>
					</table>
				</div>
				<nav aria-label="Page navigation">
					<ul class="pagination">
						<li>
							<a href="#" aria-label="Previous">
								<span aria-hidden="true">&laquo;</span>
							</a>
						</li>
						<li><a href="#">1</a></li>
						<li><a href="#">2</a></li>
						<li><a href="#">3</a></li>
						<li><a href="#">4</a></li>
						<li><a href="#">5</a></li>
						<li>
							<a href="#" aria-label="Next">
								<span aria-hidden="true">&raquo;</span>
							</a>
						</li>
					</ul>
				</nav>
			</div>
		</section>
		<div class="clearfix"></div>
<!--Main Content Area Ends-->

{% endblock content %}